### PR TITLE
Modernize and knit README

### PR DESCRIPTION
**Pull request by jdhoffa**
Seems the README has not been knit for a while. See #443 

See https://github.com/RMI-PACTA/r2dii.data/pull/323

### CODE REVIEW

**Review by jacobvjk — COMMENTED** [review]
Given that we are updating the README file, should we care about the failing check? Although the error seems to be coming from getting an R version, not directly from the rendering

**Comment by cjyetman** [comment]
> Warning: r-lib/actions/setup-r@v1 is deprecated. Please update your workflow to use the 'v2' version. Also look at the examples at https://github.com/r-lib/actions/tree/v2/examples because '@v2' workflows are much simpler than 'v1' workflows.

**Comment by jdhoffa** [comment]
See #444, I will try to fix that action there. 

Depends on #444

**Comment by jdhoffa** [comment]
Checks now passing :-)

**Review by jacobvjk — APPROVED** [review]
lgtm

**Pull request merged**
