### PR TITLE
Increment version number to 0.1.4.9000

### PR DESCRIPTION
**Pull request by jdhoffa**
Bump to dev version number.

### CODE REVIEW

**Comment by jdhoffa** [comment]
@AlexAxthelm all checks seem to be failing, is this a known problem?
(follow-up, how did we get this onto CRAN with all the checks failing?)

**Comment by AlexAxthelm** [comment]
@jdhoffa the checks look to me like they might be using the wrong version of r2dii.data?

**Comment by jdhoffa** [comment]
> @jdhoffa the checks look to me like they might be using the wrong version of r2dii.data?

Mauro wrote two different categories of tests. One test against the CRAN published version of `r2dii.data` (R-CMD-check), the other tests against the latest commit on `main` (R-CMD-check r2dii-devel)

All seem to fail.

**Comment by jdhoffa** [comment]
Yeah I also get 11 failed tests locally.

How did this make it to CRAN??? Are we sure it was accepted @AlexAxthelm  

Screenshot 2024-01-10 at 12 22 30

**Comment by jdhoffa** [comment]
Blocked by #434

**Comment by jdhoffa** [comment]
Actually, I'm going to force merge this, as whatever I do to fix these failing tests will need to be a "next release" kind of thing.

**Pull request merged**
